import { Stylist, ServiceCategory } from "./types";

/** Platform economics: clients pay a 5% booking fee, stylists keep 85% of every service. */
export const CLIENT_FEE_RATE = 0.05;
export const STYLIST_KEEP_RATE = 0.85;

export const CATEGORIES: { name: ServiceCategory; emoji: string; blurb: string }[] = [
  { name: "Wardrobe Makeover", emoji: "🧥", blurb: "A full reset of how you dress, built around your life" },
  { name: "Personal Shopping", emoji: "🛍️", blurb: "A pro shops with you or for you, on any budget" },
  { name: "Event Styling", emoji: "✨", blurb: "Weddings, galas, interviews, first dates, big stages" },
  { name: "Closet Edit", emoji: "🗂️", blurb: "Keep, tailor, donate. Leave with outfits, not piles" },
  { name: "Virtual Consult", emoji: "💻", blurb: "Expert eyes on your style from anywhere on earth" },
  { name: "Color Analysis", emoji: "🎨", blurb: "Find the palette that makes your skin light up" },
];

export const CITIES = [
  "New York",
  "Los Angeles",
  "Chicago",
  "Miami",
  "Atlanta",
  "Austin",
  "San Francisco",
  "London",
];

export const STYLISTS: Stylist[] = [
  {
    id: "amara-osei",
    name: "Amara Osei",
    handle: "@amarastyles",
    tagline: "Bold color, clean lines, zero boring outfits",
    city: "New York",
    neighborhood: "SoHo",
    rating: 4.97,
    reviewCount: 312,
    bookings: 1180,
    responseTime: "under 1 hour",
    yearsExperience: 9,
    startingPrice: 95,
    topRated: true,
    risingStar: false,
    instantBook: true,
    virtual: true,
    specialties: ["Wardrobe Makeover", "Color Analysis", "Personal Shopping"],
    languages: ["English", "French"],
    bio: "Former fashion editor turned personal stylist. I spent seven years dressing magazine shoots before realizing the most exciting transformations happen on real people with real lives. I build wardrobes that work as hard as you do.",
    approach: "We start with who you are, not what is trending. First session is a deep style audit, then we build a capsule that mixes forty ways before we ever buy anything new.",
    brands: ["COS", "Sézane", "Arket", "Toteme", "Zara Studio"],
    gradient: ["#C4593A", "#8F3A2A"],
    accent: "#E8C3B5",
    services: [
      { id: "s1", name: "Signature Wardrobe Reset", category: "Wardrobe Makeover", duration: "3 hrs", price: 285, description: "Full closet audit, style profile, capsule plan and a lookbook of 25 outfits from what you own plus a smart shopping list.", mode: "In person" },
      { id: "s2", name: "Power Hour Consult", category: "Virtual Consult", duration: "60 min", price: 95, description: "Rapid fire styling session over video. Bring your questions, your closet and your doubts.", mode: "Virtual" },
      { id: "s3", name: "Shop With Me: SoHo Edit", category: "Personal Shopping", duration: "2.5 hrs", price: 240, description: "A curated route through my favorite SoHo racks, pre pulled fitting rooms and honest opinions only.", mode: "In person" },
      { id: "s4", name: "Seasonal Color Mapping", category: "Color Analysis", duration: "90 min", price: 150, description: "Drape based color analysis with a personal palette card you can carry in your wallet forever.", mode: "In person or virtual" },
    ],
    looks: [
      { id: "l1", title: "Terracotta Tailoring", vibe: "Sharp but warm", tags: ["workwear", "tonal"], palette: ["#C4593A", "#E8C3B5", "#7A4A32", "#F3EDE3", "#181411"], emoji: "🧥" },
      { id: "l2", title: "Gallery Opening", vibe: "Art crowd polish", tags: ["evening", "statement"], palette: ["#181411", "#B8863B", "#5C4560", "#FAF7F1", "#8F3A2A"], emoji: "🖼️" },
      { id: "l3", title: "Sunday Uniform", vibe: "Effortless off duty", tags: ["casual", "capsule"], palette: ["#D6CDBF", "#7A8B6F", "#F3EDE3", "#3E3A34", "#C4593A"], emoji: "☕" },
      { id: "l4", title: "Color Confidence", vibe: "Loud on purpose", tags: ["color", "bold"], palette: ["#C4593A", "#3E5C6B", "#D9B87A", "#5C4560", "#FAF7F1"], emoji: "🎨" },
      { id: "l5", title: "The Interview Suit, Rewired", vibe: "Authority with edge", tags: ["workwear", "tailoring"], palette: ["#2A241F", "#B8863B", "#EAE1D3", "#6B6259", "#C4593A"], emoji: "💼" },
      { id: "l6", title: "City Weekend Capsule", vibe: "Ten pieces, one carry on", tags: ["travel", "capsule"], palette: ["#F3EDE3", "#181411", "#C4593A", "#7A8B6F", "#D9B87A"], emoji: "🧳" },
    ],
    reviews: [
      { id: "r1", author: "Danielle M.", rating: 5, date: "May 2026", service: "Signature Wardrobe Reset", text: "Amara looked at a closet I hated and found 25 outfits inside it. I cried a little. Then we donated six trash bags and I have never dressed better." },
      { id: "r2", author: "Priya S.", rating: 5, date: "April 2026", service: "Seasonal Color Mapping", text: "Turns out I have been wearing the wrong black my whole life. The palette card lives in my wallet and shopping is suddenly easy." },
      { id: "r3", author: "Jordan K.", rating: 4.8, date: "April 2026", service: "Shop With Me: SoHo Edit", text: "Worth every dollar. She had fitting rooms pulled before we arrived and vetoed two expensive mistakes I absolutely would have made." },
    ],
    nextAvailable: "Tomorrow",
  },
  {
    id: "luca-moretti",
    name: "Luca Moretti",
    handle: "@lucatailored",
    tagline: "Milanese tailoring instincts for everyday life",
    city: "New York",
    neighborhood: "West Village",
    rating: 4.92,
    reviewCount: 204,
    bookings: 760,
    responseTime: "about 2 hours",
    yearsExperience: 12,
    startingPrice: 110,
    topRated: true,
    risingStar: false,
    instantBook: false,
    virtual: true,
    specialties: ["Event Styling", "Wardrobe Makeover", "Personal Shopping"],
    languages: ["English", "Italian"],
    bio: "I grew up in my grandfather's tailor shop outside Milan and spent a decade styling menswear campaigns. Fit is ninety percent of style, and I will teach you the other ten percent too.",
    approach: "Everything begins at the tailor. We measure, we adjust, we edit. Then we shop slowly and buy fewer, better things that fit like they were made for you.",
    brands: ["Suitsupply", "Drake's", "Uniqlo U", "Massimo Dutti", "Velasca"],
    gradient: ["#3E5C6B", "#22333C"],
    accent: "#C9D8DF",
    services: [
      { id: "s1", name: "The Perfect Fit Session", category: "Wardrobe Makeover", duration: "2.5 hrs", price: 260, description: "We audit fit across your entire wardrobe, pin what can be saved and build your tailoring roadmap.", mode: "In person" },
      { id: "s2", name: "Black Tie and Beyond", category: "Event Styling", duration: "2 hrs", price: 320, description: "Wedding, gala or award night. Full look sourcing including accessories, with a fitting before the day.", mode: "In person" },
      { id: "s3", name: "Virtual Fit Check", category: "Virtual Consult", duration: "45 min", price: 110, description: "Try things on camera and I will tell you exactly what a tailor should do with each piece.", mode: "Virtual" },
    ],
    looks: [
      { id: "l1", title: "Unstructured Navy", vibe: "Boardroom to aperitivo", tags: ["tailoring", "workwear"], palette: ["#22333C", "#C9D8DF", "#B8863B", "#FAF7F1", "#6B6259"], emoji: "🕴️" },
      { id: "l2", title: "Groom, Not Groomsman", vibe: "Stand out quietly", tags: ["wedding", "evening"], palette: ["#181411", "#EAE1D3", "#3E5C6B", "#D9B87A", "#2A241F"], emoji: "🤵" },
      { id: "l3", title: "Weekend in Portofino", vibe: "Linen and loafers", tags: ["travel", "casual"], palette: ["#F3EDE3", "#3E5C6B", "#C4593A", "#D6CDBF", "#FAF7F1"], emoji: "⛵" },
      { id: "l4", title: "The Five Figure Look for $400", vibe: "High low mastery", tags: ["budget", "tailoring"], palette: ["#2A241F", "#6B6259", "#C9D8DF", "#B8863B", "#EAE1D3"], emoji: "🧵" },
      { id: "l5", title: "First Date Armor", vibe: "Relaxed confidence", tags: ["casual", "date"], palette: ["#3E5C6B", "#EAE1D3", "#181411", "#7A8B6F", "#D9B87A"], emoji: "🌹" },
    ],
    reviews: [
      { id: "r1", author: "Marcus T.", rating: 5, date: "June 2026", service: "Black Tie and Beyond", text: "Got married looking better than I have ever looked in my life. Luca even briefed the tailor himself. Absolute professional." },
      { id: "r2", author: "David R.", rating: 5, date: "May 2026", service: "The Perfect Fit Session", text: "He saved me thousands by fixing what I owned instead of replacing it. My suits from 2019 look brand new and actually fit." },
      { id: "r3", author: "Anthony B.", rating: 4.7, date: "March 2026", service: "Virtual Fit Check", text: "45 minutes and I finally understand why nothing ever looked right on me. Sleeve length. It was always sleeve length." },
    ],
    nextAvailable: "Thu",
  },
  {
    id: "sofia-reyes",
    name: "Sofia Reyes",
    handle: "@sofiastyled",
    tagline: "Curves styled with confidence and joy",
    city: "Miami",
    neighborhood: "Wynwood",
    rating: 4.99,
    reviewCount: 421,
    bookings: 1490,
    responseTime: "under 1 hour",
    yearsExperience: 8,
    startingPrice: 85,
    topRated: true,
    risingStar: false,
    instantBook: true,
    virtual: true,
    specialties: ["Wardrobe Makeover", "Event Styling", "Virtual Consult"],
    languages: ["English", "Spanish"],
    bio: "Body positive stylist specializing in curve styling and helping women fall back in love with getting dressed. Ten thousand fitting rooms later, I promise the clothes are the problem, not you.",
    approach: "No rules about what you can and cannot wear. We find silhouettes that make you feel powerful, then we make them repeatable so every morning is easy.",
    brands: ["Good American", "Eloquii", "Mango", "Reformation", "Universal Standard"],
    gradient: ["#5C4560", "#3A2B3E"],
    accent: "#D9CCDC",
    services: [
      { id: "s1", name: "Fall Back in Love Makeover", category: "Wardrobe Makeover", duration: "3 hrs", price: 250, description: "A judgment free closet overhaul focused on fit, silhouette and joy. Includes a styled outfit archive on your phone.", mode: "In person" },
      { id: "s2", name: "Big Night Energy", category: "Event Styling", duration: "2 hrs", price: 220, description: "Sourced looks for your event with backup options, plus accessories and shapewear guidance nobody else will give you straight.", mode: "In person" },
      { id: "s3", name: "Virtual Style Therapy", category: "Virtual Consult", duration: "60 min", price: 85, description: "Video session covering your fit struggles, brands that actually cut for curves and a mini plan you can act on this week.", mode: "Virtual" },
      { id: "s4", name: "Vacation Capsule Build", category: "Personal Shopping", duration: "2 hrs", price: 190, description: "Resort ready capsule shopped to your budget. Every piece mixes with every other piece.", mode: "In person or virtual" },
    ],
    looks: [
      { id: "l1", title: "Wynwood Nights", vibe: "Tropical drama", tags: ["evening", "color"], palette: ["#5C4560", "#C4593A", "#D9B87A", "#181411", "#D9CCDC"], emoji: "🌴" },
      { id: "l2", title: "The Wrap Dress Rebellion", vibe: "Beyond the obvious", tags: ["curve", "statement"], palette: ["#8F3A2A", "#D9CCDC", "#2A241F", "#F3EDE3", "#B8863B"], emoji: "💃" },
      { id: "l3", title: "Boardroom Bombshell", vibe: "Power dressing, curved", tags: ["workwear", "curve"], palette: ["#2A241F", "#5C4560", "#EAE1D3", "#B8863B", "#6B6259"], emoji: "💼" },
      { id: "l4", title: "Beach to Dinner", vibe: "One bag, two lives", tags: ["travel", "casual"], palette: ["#D9B87A", "#3E5C6B", "#FAF7F1", "#C4593A", "#7A8B6F"], emoji: "🏖️" },
      { id: "l5", title: "Denim, Finally", vibe: "Jeans that fit for real", tags: ["casual", "curve"], palette: ["#3E5C6B", "#C9D8DF", "#181411", "#F3EDE3", "#C4593A"], emoji: "👖" },
      { id: "l6", title: "Quinceañera Madrina", vibe: "Celebration royalty", tags: ["event", "family"], palette: ["#5C4560", "#D9B87A", "#8F3A2A", "#FAF7F1", "#181411"], emoji: "👑" },
    ],
    reviews: [
      { id: "r1", author: "Camila V.", rating: 5, date: "June 2026", service: "Fall Back in Love Makeover", text: "I have not worn a dress in six years. Sofia had me in one within an hour and I felt incredible. She changed my relationship with my own closet." },
      { id: "r2", author: "Ashley D.", rating: 5, date: "May 2026", service: "Big Night Energy", text: "Showed up to my reunion feeling like the main character. Three people asked who dressed me. HER. She dressed me." },
      { id: "r3", author: "Renata L.", rating: 5, date: "May 2026", service: "Virtual Style Therapy", text: "One hour on video was more useful than years of buying and returning. She named my exact fit issue in ten minutes." },
    ],
    nextAvailable: "Today",
  },
  {
    id: "kenji-tanaka",
    name: "Kenji Tanaka",
    handle: "@kenjiminimal",
    tagline: "Quiet luxury and capsule wardrobes that travel",
    city: "San Francisco",
    neighborhood: "Hayes Valley",
    rating: 4.9,
    reviewCount: 178,
    bookings: 640,
    responseTime: "about 3 hours",
    yearsExperience: 7,
    startingPrice: 100,
    topRated: false,
    risingStar: false,
    instantBook: true,
    virtual: true,
    specialties: ["Closet Edit", "Wardrobe Makeover", "Virtual Consult"],
    languages: ["English", "Japanese"],
    bio: "Ex product designer who applies systems thinking to closets. My clients are founders, engineers and anyone who wants to look considered without thinking about clothes every morning.",
    approach: "Style as a system: a tight palette, interchangeable silhouettes and a strict one in one out rule. Decision fatigue dies here.",
    brands: ["Everlane", "Muji", "Lemaire", "Our Legacy", "Patagonia"],
    gradient: ["#7A8B6F", "#4A5843"],
    accent: "#D6DDCD",
    services: [
      { id: "s1", name: "The 33 Piece System", category: "Closet Edit", duration: "3 hrs", price: 270, description: "We reduce your wardrobe to a working system of about 33 pieces that produce 100 plus outfits. Includes a digital outfit matrix.", mode: "In person" },
      { id: "s2", name: "Founder Uniform Design", category: "Wardrobe Makeover", duration: "2 hrs", price: 230, description: "A signature daily uniform engineered for your body, calendar and climate. Never think about Monday again.", mode: "In person or virtual" },
      { id: "s3", name: "Async Closet Review", category: "Virtual Consult", duration: "Async + 30 min call", price: 100, description: "Send photos of everything. Receive a keep, tailor, release plan plus a 30 minute walkthrough call.", mode: "Virtual" },
    ],
    looks: [
      { id: "l1", title: "The Daily Uniform", vibe: "One decision, done", tags: ["capsule", "minimal"], palette: ["#4A5843", "#EAE1D3", "#181411", "#D6DDCD", "#6B6259"], emoji: "📐" },
      { id: "l2", title: "Demo Day", vibe: "Credible, not corporate", tags: ["workwear", "minimal"], palette: ["#2A241F", "#D6DDCD", "#3E5C6B", "#F3EDE3", "#B8863B"], emoji: "🚀" },
      { id: "l3", title: "Kyoto Carry On", vibe: "Two weeks, eight pieces", tags: ["travel", "capsule"], palette: ["#7A8B6F", "#F3EDE3", "#2A241F", "#C9D8DF", "#D9B87A"], emoji: "🎋" },
      { id: "l4", title: "Texture Over Logo", vibe: "Quiet luxury", tags: ["minimal", "luxury"], palette: ["#EAE1D3", "#6B6259", "#181411", "#D6CDBF", "#7A8B6F"], emoji: "🧶" },
      { id: "l5", title: "Fog City Layers", vibe: "SF microclimate proof", tags: ["casual", "layering"], palette: ["#6B6259", "#C9D8DF", "#4A5843", "#F3EDE3", "#2A241F"], emoji: "🌫️" },
    ],
    reviews: [
      { id: "r1", author: "Wei Z.", rating: 5, date: "June 2026", service: "The 33 Piece System", text: "The outfit matrix spreadsheet alone is worth the price. I got dressed in 90 seconds every day this month and looked better than ever." },
      { id: "r2", author: "Sam H.", rating: 4.8, date: "April 2026", service: "Founder Uniform Design", text: "Kenji designed me a uniform that survives board meetings and bike commutes. People think I hired a brand consultant. I basically did." },
      { id: "r3", author: "Nina P.", rating: 4.9, date: "March 2026", service: "Async Closet Review", text: "The async format is perfect. Sent photos Sunday, had a full ruthless and correct plan by Wednesday." },
    ],
    nextAvailable: "Tomorrow",
  },
  {
    id: "zara-bennett",
    name: "Zara Bennett",
    handle: "@zarabstyle",
    tagline: "Street style edge for your nine to five",
    city: "London",
    neighborhood: "Shoreditch",
    rating: 4.88,
    reviewCount: 156,
    bookings: 520,
    responseTime: "about 2 hours",
    yearsExperience: 6,
    startingPrice: 90,
    topRated: false,
    risingStar: true,
    instantBook: true,
    virtual: true,
    specialties: ["Personal Shopping", "Wardrobe Makeover", "Event Styling"],
    languages: ["English"],
    bio: "Started styling music videos in East London, now I bring that same energy to people who feel invisible in their own clothes. Your style should start conversations.",
    approach: "We find your one signature move: a color, a silhouette, a piece you always wear your way. Then we build everything else around it.",
    brands: ["COS", "Stüssy", "Ganni", "Carhartt WIP", "& Other Stories"],
    gradient: ["#B8863B", "#7A5622"],
    accent: "#D9B87A",
    services: [
      { id: "s1", name: "Signature Move Session", category: "Wardrobe Makeover", duration: "2.5 hrs", price: 240, description: "We identify the style signature that makes you unmistakable, then rebuild your rotation around it.", mode: "In person" },
      { id: "s2", name: "East London Crawl", category: "Personal Shopping", duration: "3 hrs", price: 210, description: "Vintage, archive and new wave shops across Shoreditch and Dalston. Come home with pieces nobody else owns.", mode: "In person" },
      { id: "s3", name: "Festival and Gig Styling", category: "Event Styling", duration: "90 min", price: 160, description: "Stage ready or crowd ready looks that survive a full day on your feet.", mode: "In person or virtual" },
      { id: "s4", name: "Style Jumpstart Call", category: "Virtual Consult", duration: "60 min", price: 90, description: "One hour to break you out of your style rut with three concrete outfit formulas.", mode: "Virtual" },
    ],
    looks: [
      { id: "l1", title: "Office, But Make It East", vibe: "Corporate with a wink", tags: ["workwear", "street"], palette: ["#181411", "#D9B87A", "#3E5C6B", "#F3EDE3", "#C4593A"], emoji: "🎧" },
      { id: "l2", title: "Vintage Leather Everything", vibe: "Found, not bought", tags: ["vintage", "statement"], palette: ["#7A5622", "#2A241F", "#EAE1D3", "#8F3A2A", "#B8863B"], emoji: "🧥" },
      { id: "l3", title: "Glasto Ready", vibe: "Mud proof style", tags: ["festival", "casual"], palette: ["#7A8B6F", "#B8863B", "#181411", "#D6DDCD", "#C4593A"], emoji: "🎪" },
      { id: "l4", title: "Trainers With Everything", vibe: "The right pair changes it all", tags: ["street", "casual"], palette: ["#F3EDE3", "#181411", "#C4593A", "#C9D8DF", "#D9B87A"], emoji: "👟" },
      { id: "l5", title: "Pub to Private View", vibe: "One outfit, two worlds", tags: ["evening", "street"], palette: ["#2A241F", "#5C4560", "#D9B87A", "#FAF7F1", "#6B6259"], emoji: "🍸" },
    ],
    reviews: [
      { id: "r1", author: "Ollie F.", rating: 5, date: "May 2026", service: "East London Crawl", text: "Zara knows every rack in East London. Found a vintage jacket I get stopped about weekly. Cost me forty quid." },
      { id: "r2", author: "Tasha W.", rating: 4.8, date: "May 2026", service: "Signature Move Session", text: "She figured out my signature was collars. COLLARS. And she was completely right, my whole wardrobe clicked into place." },
      { id: "r3", author: "Jamie C.", rating: 4.7, date: "April 2026", service: "Style Jumpstart Call", text: "Three outfit formulas that actually work with clothes I already had. Been out of my rut for a month now." },
    ],
    nextAvailable: "Today",
  },
  {
    id: "marcus-cole",
    name: "Marcus Cole",
    handle: "@colestyled",
    tagline: "Grown man style without the guesswork",
    city: "Atlanta",
    neighborhood: "Midtown",
    rating: 4.94,
    reviewCount: 267,
    bookings: 890,
    responseTime: "under 1 hour",
    yearsExperience: 11,
    startingPrice: 80,
    topRated: true,
    risingStar: false,
    instantBook: true,
    virtual: true,
    specialties: ["Wardrobe Makeover", "Personal Shopping", "Event Styling"],
    languages: ["English"],
    bio: "I style men who succeeded at everything except getting dressed. Executives, athletes, dads, grooms. No judgment, just a system that makes you look like the man you already are.",
    approach: "Three sessions, lifetime results. Audit what you own, fill the five gaps every man has, then learn the formulas so you never need me again. Most of my clients still come back.",
    brands: ["J.Crew", "Todd Snyder", "Buck Mason", "Nike", "Banana Republic"],
    gradient: ["#2A241F", "#181411"],
    accent: "#B8863B",
    services: [
      { id: "s1", name: "The Grown Man Reset", category: "Wardrobe Makeover", duration: "3 hrs", price: 265, description: "Closet audit, gap analysis and the five formulas that solve 95 percent of your week. Includes a phone lookbook.", mode: "In person" },
      { id: "s2", name: "Date Night Draft", category: "Event Styling", duration: "90 min", price: 140, description: "Look sourced and styled for the night that matters. Confidence included.", mode: "In person or virtual" },
      { id: "s3", name: "90 Minute Mall Run", category: "Personal Shopping", duration: "90 min", price: 130, description: "Efficient, budget respecting shopping trip. We get in, we win, we get out.", mode: "In person" },
      { id: "s4", name: "Style Foundations Call", category: "Virtual Consult", duration: "45 min", price: 80, description: "Fit, color and the three purchases that would change your look immediately.", mode: "Virtual" },
    ],
    looks: [
      { id: "l1", title: "Church to Brunch", vibe: "Southern polish", tags: ["tailoring", "weekend"], palette: ["#2A241F", "#B8863B", "#EAE1D3", "#3E5C6B", "#FAF7F1"], emoji: "🕊️" },
      { id: "l2", title: "Courtside Clean", vibe: "Athlete off duty", tags: ["street", "casual"], palette: ["#181411", "#C4593A", "#F3EDE3", "#6B6259", "#D9B87A"], emoji: "🏀" },
      { id: "l3", title: "The Second First Impression", vibe: "Reunion ready", tags: ["event", "tailoring"], palette: ["#3E5C6B", "#EAE1D3", "#181411", "#B8863B", "#C9D8DF"], emoji: "🥂" },
      { id: "l4", title: "Dad Uniform, Upgraded", vibe: "Playground approved", tags: ["casual", "capsule"], palette: ["#7A8B6F", "#F3EDE3", "#2A241F", "#C4593A", "#D6CDBF"], emoji: "🛝" },
      { id: "l5", title: "All Black Everything, Done Right", vibe: "Texture is the trick", tags: ["minimal", "evening"], palette: ["#181411", "#2A241F", "#6B6259", "#3E3A34", "#B8863B"], emoji: "🖤" },
      { id: "l6", title: "Groom Squad", vibe: "Five men, one vision", tags: ["wedding", "group"], palette: ["#2A241F", "#D9B87A", "#EAE1D3", "#5C4560", "#FAF7F1"], emoji: "💍" },
    ],
    reviews: [
      { id: "r1", author: "Terrence W.", rating: 5, date: "June 2026", service: "The Grown Man Reset", text: "43 years old and I finally know how to dress. Marcus gave me formulas, not rules. My wife keeps asking what got into me." },
      { id: "r2", author: "DeShawn R.", rating: 5, date: "May 2026", service: "Date Night Draft", text: "She said yes to date two before date one was over. I am giving the outfit at least 30 percent of the credit." },
      { id: "r3", author: "Kevin O.", rating: 4.8, date: "April 2026", service: "90 Minute Mall Run", text: "In and out in 85 minutes with a month of outfits. This man shops like a heist crew runs a job." },
    ],
    nextAvailable: "Today",
  },
  {
    id: "ines-laurent",
    name: "Inès Laurent",
    handle: "@ineslaurent",
    tagline: "Parisian ease, translated for your real life",
    city: "New York",
    neighborhood: "Upper East Side",
    rating: 4.95,
    reviewCount: 289,
    bookings: 940,
    responseTime: "about 2 hours",
    yearsExperience: 14,
    startingPrice: 130,
    topRated: true,
    risingStar: false,
    instantBook: false,
    virtual: true,
    specialties: ["Wardrobe Makeover", "Personal Shopping", "Color Analysis"],
    languages: ["English", "French"],
    bio: "Fourteen years dressing private clients in Paris and New York. I believe in fewer clothes, better fabric and the confidence that comes from knowing exactly what suits you.",
    approach: "Elegance is refusal. We remove everything that is almost right so what remains is exactly right. Then we invest slowly in pieces you will wear for a decade.",
    brands: ["Sézane", "A.P.C.", "Vince", "The Row", "Rouje"],
    gradient: ["#181411", "#3A2B3E"],
    accent: "#D9CCDC",
    services: [
      { id: "s1", name: "L'Édit: Complete Wardrobe Cure", category: "Wardrobe Makeover", duration: "4 hrs", price: 420, description: "My signature service. Ruthless edit, silhouette study, fabric education and a ten year investment plan for your wardrobe.", mode: "In person" },
      { id: "s2", name: "Madison Avenue Appointment", category: "Personal Shopping", duration: "2.5 hrs", price: 340, description: "Private shopping with pre arranged pulls at my favorite houses. Champagne optional but encouraged.", mode: "In person" },
      { id: "s3", name: "Le Regard: Color and Silhouette Study", category: "Color Analysis", duration: "2 hrs", price: 230, description: "Classical drape analysis plus silhouette mapping. You leave with a personal style charter, printed and bound.", mode: "In person" },
      { id: "s4", name: "Paris on a Screen", category: "Virtual Consult", duration: "60 min", price: 130, description: "A precise, honest hour on what to keep, what to release and what one piece to buy next.", mode: "Virtual" },
    ],
    looks: [
      { id: "l1", title: "La Base Parfaite", vibe: "Ten flawless staples", tags: ["capsule", "luxury"], palette: ["#181411", "#EAE1D3", "#6B6259", "#FAF7F1", "#B8863B"], emoji: "🥐" },
      { id: "l2", title: "Silk at Noon", vibe: "Daylight glamour", tags: ["luxury", "daytime"], palette: ["#D9CCDC", "#181411", "#D9B87A", "#F3EDE3", "#5C4560"], emoji: "🎀" },
      { id: "l3", title: "The Trench Thesis", vibe: "One coat, whole personality", tags: ["outerwear", "classic"], palette: ["#D6CDBF", "#2A241F", "#EAE1D3", "#8F3A2A", "#B8863B"], emoji: "🧭" },
      { id: "l4", title: "Dinner at Nine", vibe: "Understated evening", tags: ["evening", "minimal"], palette: ["#2A241F", "#5C4560", "#FAF7F1", "#B8863B", "#181411"], emoji: "🕯️" },
      { id: "l5", title: "Wrong Shoe Theory", vibe: "The deliberate clash", tags: ["statement", "playful"], palette: ["#F3EDE3", "#C4593A", "#181411", "#C9D8DF", "#D9B87A"], emoji: "👠" },
    ],
    reviews: [
      { id: "r1", author: "Whitney A.", rating: 5, date: "June 2026", service: "L'Édit: Complete Wardrobe Cure", text: "Inès removed 60 percent of my closet and somehow I have more to wear. The printed style charter is the most useful document I own." },
      { id: "r2", author: "Grace L.", rating: 5, date: "April 2026", service: "Madison Avenue Appointment", text: "The pulls were waiting, the champagne was cold and every single piece was right. Spent less than I expected because nothing was a maybe." },
      { id: "r3", author: "Elena F.", rating: 4.8, date: "March 2026", service: "Paris on a Screen", text: "She is precise and honest in the way only a French stylist can be. One hour rearranged how I think about buying clothes." },
    ],
    nextAvailable: "Fri",
  },
  {
    id: "dani-park",
    name: "Dani Park",
    handle: "@danistyles",
    tagline: "Gender free styling for exactly who you are",
    city: "Los Angeles",
    neighborhood: "Silver Lake",
    rating: 4.96,
    reviewCount: 198,
    bookings: 610,
    responseTime: "under 1 hour",
    yearsExperience: 5,
    startingPrice: 75,
    topRated: false,
    risingStar: true,
    instantBook: true,
    virtual: true,
    specialties: ["Wardrobe Makeover", "Virtual Consult", "Personal Shopping"],
    languages: ["English", "Korean"],
    bio: "Styling beyond the binary. I help clients of every identity build wardrobes that feel like home, whether you are exploring your expression for the first time or refining it.",
    approach: "Clothes are a language and you get to choose your words. Sessions are private, affirming and paced entirely by you. No fitting room is ever rushed.",
    brands: ["Wildfang", "Uniqlo", "Big Bud Press", "Levi's", "Telfar"],
    gradient: ["#3E5C6B", "#5C4560"],
    accent: "#C9D8DF",
    services: [
      { id: "s1", name: "True Mirror Session", category: "Wardrobe Makeover", duration: "3 hrs", price: 225, description: "A gentle full wardrobe rebuild aligned with your identity and comfort. Includes silhouette and fit coaching.", mode: "In person" },
      { id: "s2", name: "First Steps Consult", category: "Virtual Consult", duration: "75 min", price: 75, description: "A safe, private video session for anyone starting to explore their style expression. Zero pressure, real guidance.", mode: "Virtual" },
      { id: "s3", name: "Eastside Thrift Quest", category: "Personal Shopping", duration: "2.5 hrs", price: 165, description: "Silver Lake and Echo Park vintage circuit. Sustainable, affordable and completely one of a kind.", mode: "In person" },
    ],
    looks: [
      { id: "l1", title: "Soft Structure", vibe: "Sharp shoulders, easy heart", tags: ["androgynous", "tailoring"], palette: ["#3E5C6B", "#F3EDE3", "#181411", "#D9CCDC", "#B8863B"], emoji: "🌗" },
      { id: "l2", title: "Sunday Skate", vibe: "Silver Lake casual", tags: ["street", "casual"], palette: ["#C9D8DF", "#C4593A", "#2A241F", "#D6DDCD", "#F3EDE3"], emoji: "🛹" },
      { id: "l3", title: "First Pride", vibe: "Loud, proud, comfortable", tags: ["event", "color"], palette: ["#C4593A", "#B8863B", "#7A8B6F", "#3E5C6B", "#5C4560"], emoji: "🏳️‍🌈" },
      { id: "l4", title: "The New Interview", vibe: "Professional on your terms", tags: ["workwear", "androgynous"], palette: ["#2A241F", "#C9D8DF", "#EAE1D3", "#5C4560", "#6B6259"], emoji: "📎" },
      { id: "l5", title: "Vintage Denim Head to Toe", vibe: "Found treasure", tags: ["vintage", "denim"], palette: ["#3E5C6B", "#C9D8DF", "#8F3A2A", "#F3EDE3", "#181411"], emoji: "🧢" },
    ],
    reviews: [
      { id: "r1", author: "Alex J.", rating: 5, date: "June 2026", service: "True Mirror Session", text: "I saw myself in the mirror for the first time. Actually me. I do not have words for what Dani gave me in three hours." },
      { id: "r2", author: "Morgan T.", rating: 5, date: "May 2026", service: "First Steps Consult", text: "I was nervous for weeks and comfortable in five minutes. Left with a plan, three shop links and a lot less fear." },
      { id: "r3", author: "Casey R.", rating: 4.9, date: "April 2026", service: "Eastside Thrift Quest", text: "Dani can read a thrift rack like a stock ticker. Whole new look for under $120, and nobody else on earth has my jacket." },
    ],
    nextAvailable: "Tomorrow",
  },
  {
    id: "harper-quinn",
    name: "Harper Quinn",
    handle: "@harperonset",
    tagline: "Red carpet training for your biggest moments",
    city: "Los Angeles",
    neighborhood: "West Hollywood",
    rating: 4.91,
    reviewCount: 143,
    bookings: 430,
    responseTime: "about 4 hours",
    yearsExperience: 10,
    startingPrice: 150,
    topRated: false,
    risingStar: false,
    instantBook: false,
    virtual: true,
    specialties: ["Event Styling", "Personal Shopping", "Wardrobe Makeover"],
    languages: ["English"],
    bio: "Celebrity stylist with a decade of premieres, press tours and award shows. Between seasons I style civilians for the nights they will remember forever, with the same playbook the talent gets.",
    approach: "Every big moment gets the full treatment: mood board, sourcing, fittings, tailoring and a day of emergency kit. You will feel like the photos are the easy part.",
    brands: ["Net-a-Porter", "Rent the Runway", "Saks", "The RealReal", "Revolve"],
    gradient: ["#8F3A2A", "#5C1F14"],
    accent: "#E8C3B5",
    services: [
      { id: "s1", name: "The Premiere Package", category: "Event Styling", duration: "2 sessions + event day", price: 480, description: "Mood board, two sourcing rounds, fitting, tailoring coordination and an on call styling kit the day of.", mode: "In person" },
      { id: "s2", name: "Camera Ready Consult", category: "Virtual Consult", duration: "60 min", price: 150, description: "Headshots, weddings, launches or TV. What reads well on camera and what disappears.", mode: "Virtual" },
      { id: "s3", name: "Rodeo Drive Recon", category: "Personal Shopping", duration: "3 hrs", price: 390, description: "High end sourcing session with showroom access most shoppers never see.", mode: "In person" },
    ],
    looks: [
      { id: "l1", title: "Step and Repeat", vibe: "Flashbulb proof", tags: ["red carpet", "evening"], palette: ["#8F3A2A", "#181411", "#D9B87A", "#FAF7F1", "#E8C3B5"], emoji: "📸" },
      { id: "l2", title: "The Engagement Shoot", vibe: "Timeless in ten years", tags: ["event", "couple"], palette: ["#EAE1D3", "#5C4560", "#B8863B", "#F3EDE3", "#2A241F"], emoji: "💞" },
      { id: "l3", title: "Press Tour Day Three", vibe: "Fresh when exhausted", tags: ["workwear", "camera"], palette: ["#2A241F", "#C9D8DF", "#8F3A2A", "#EAE1D3", "#B8863B"], emoji: "🎬" },
      { id: "l4", title: "Gala, But Comfortable", vibe: "Four hours in heels, smiling", tags: ["evening", "gala"], palette: ["#181411", "#D9B87A", "#5C4560", "#FAF7F1", "#8F3A2A"], emoji: "🏆" },
      { id: "l5", title: "The Rented Masterpiece", vibe: "Five figures of look, three figures of spend", tags: ["rental", "evening"], palette: ["#5C4560", "#E8C3B5", "#181411", "#B8863B", "#F3EDE3"], emoji: "💎" },
    ],
    reviews: [
      { id: "r1", author: "Vanessa H.", rating: 5, date: "May 2026", service: "The Premiere Package", text: "My book launch photos look like a magazine spread. The emergency kit saved the night when a heel strap snapped. She had thought of it already." },
      { id: "r2", author: "Chloe B.", rating: 4.9, date: "April 2026", service: "Rodeo Drive Recon", text: "Showrooms I did not know existed. Harper negotiated a rental on a gown that was not even listed for rent." },
      { id: "r3", author: "Mia S.", rating: 4.7, date: "February 2026", service: "Camera Ready Consult", text: "Everything she said about camera fabrics was right. My headshots came back and I did not want to retouch a thing." },
    ],
    nextAvailable: "Next week",
  },
  {
    id: "tobias-berg",
    name: "Tobias Berg",
    handle: "@bergwardrobe",
    tagline: "Scandinavian function meets sharp design",
    city: "Chicago",
    neighborhood: "Wicker Park",
    rating: 4.86,
    reviewCount: 121,
    bookings: 380,
    responseTime: "about 3 hours",
    yearsExperience: 8,
    startingPrice: 85,
    topRated: false,
    risingStar: false,
    instantBook: true,
    virtual: true,
    specialties: ["Closet Edit", "Wardrobe Makeover", "Virtual Consult"],
    languages: ["English", "Swedish", "German"],
    bio: "Stockholm born, Chicago frozen. I build wardrobes that survive real winters and real life without surrendering an inch of style. Function is not the opposite of fashion.",
    approach: "Layering is architecture. We design your wardrobe from the base layer out so you look intentional at minus ten and at room temperature after the coat comes off.",
    brands: ["Norse Projects", "Fjällräven", "Acne Studios", "Filson", "Icebreaker"],
    gradient: ["#4A5843", "#2E3829"],
    accent: "#D6DDCD",
    services: [
      { id: "s1", name: "Four Season Architecture", category: "Wardrobe Makeover", duration: "3 hrs", price: 245, description: "A layering system engineered for brutal winters and humid summers, built from your existing wardrobe up.", mode: "In person" },
      { id: "s2", name: "The Great Purge", category: "Closet Edit", duration: "2.5 hrs", price: 195, description: "Decisive closet edit with a resale plan. Average client recovers $300 selling what we release.", mode: "In person" },
      { id: "s3", name: "Cold Climate Consult", category: "Virtual Consult", duration: "45 min", price: 85, description: "Outerwear, boots and layers that actually work, whatever your city throws at you.", mode: "Virtual" },
    ],
    looks: [
      { id: "l1", title: "Minus Ten, Still Sharp", vibe: "Winter armor", tags: ["outerwear", "winter"], palette: ["#2E3829", "#EAE1D3", "#181411", "#B8863B", "#D6DDCD"], emoji: "❄️" },
      { id: "l2", title: "The Lake Effect Layer", vibe: "Three layers, one silhouette", tags: ["layering", "casual"], palette: ["#4A5843", "#C9D8DF", "#2A241F", "#F3EDE3", "#6B6259"], emoji: "🌬️" },
      { id: "l3", title: "Cabin Weekend", vibe: "Wool and firelight", tags: ["weekend", "texture"], palette: ["#7A5622", "#2E3829", "#EAE1D3", "#8F3A2A", "#D6CDBF"], emoji: "🪵" },
      { id: "l4", title: "Office Thaw", vibe: "Coat off, still composed", tags: ["workwear", "layering"], palette: ["#2A241F", "#D6DDCD", "#3E5C6B", "#EAE1D3", "#B8863B"], emoji: "🧣" },
      { id: "l5", title: "Nordic Summer", vibe: "Light, long evenings", tags: ["summer", "minimal"], palette: ["#F3EDE3", "#C9D8DF", "#7A8B6F", "#FAF7F1", "#181411"], emoji: "🌤️" },
    ],
    reviews: [
      { id: "r1", author: "Erik N.", rating: 5, date: "May 2026", service: "Four Season Architecture", text: "First winter of my life where I was warm AND well dressed. The layering diagrams he leaves you are genius." },
      { id: "r2", author: "Hannah G.", rating: 4.8, date: "April 2026", service: "The Great Purge", text: "Sold $340 of clothes I never wore using his resale plan. The session paid for itself and my closet finally breathes." },
      { id: "r3", author: "Piotr K.", rating: 4.6, date: "March 2026", service: "Cold Climate Consult", text: "Precise and practical. He talked me out of a $900 parka and into a $340 setup that works better." },
    ],
    nextAvailable: "Wed",
  },
  {
    id: "priya-anand",
    name: "Priya Anand",
    handle: "@priyaanandstyle",
    tagline: "Where heritage meets high fashion",
    city: "Austin",
    neighborhood: "South Congress",
    rating: 4.93,
    reviewCount: 187,
    bookings: 560,
    responseTime: "under 1 hour",
    yearsExperience: 7,
    startingPrice: 90,
    topRated: true,
    risingStar: false,
    instantBook: true,
    virtual: true,
    specialties: ["Event Styling", "Wardrobe Makeover", "Color Analysis"],
    languages: ["English", "Hindi", "Tamil"],
    bio: "I specialize in fusion styling: honoring where you come from while dressing for where you are going. From boardrooms to shaadi season, I keep both worlds beautiful.",
    approach: "Your heritage is a design asset, not a constraint. We blend traditional textiles, modern silhouettes and your personal story into a wardrobe that could only belong to you.",
    brands: ["Anthropologie", "Sabyasachi inspired", "Madewell", "Block Shop", "Free People"],
    gradient: ["#B8863B", "#8F3A2A"],
    accent: "#D9B87A",
    services: [
      { id: "s1", name: "Shaadi Season Styling", category: "Event Styling", duration: "2 hrs per event", price: 260, description: "Sangeet, mehndi, reception or guest looks. Traditional, fusion or fully modern, styled to photograph beautifully.", mode: "In person or virtual" },
      { id: "s2", name: "Two Worlds Wardrobe", category: "Wardrobe Makeover", duration: "3 hrs", price: 240, description: "A wardrobe system that moves fluidly between cultural events and everyday life without feeling like two closets.", mode: "In person" },
      { id: "s3", name: "Jewel Tone Analysis", category: "Color Analysis", duration: "90 min", price: 140, description: "Color analysis with deep expertise in rich skin tones, gold versus silver, and the jewel tones fast fashion ignores.", mode: "In person or virtual" },
      { id: "s4", name: "Quick Fusion Consult", category: "Virtual Consult", duration: "45 min", price: 90, description: "Fast answers on blending traditional pieces into modern outfits, or building an event look remotely.", mode: "Virtual" },
    ],
    looks: [
      { id: "l1", title: "Sangeet Under the Stars", vibe: "Dance floor durable", tags: ["wedding", "traditional"], palette: ["#8F3A2A", "#D9B87A", "#5C4560", "#B8863B", "#FAF7F1"], emoji: "🪩" },
      { id: "l2", title: "The Silk Blazer Fusion", vibe: "Heirloom meets office", tags: ["fusion", "workwear"], palette: ["#B8863B", "#2A241F", "#EAE1D3", "#8F3A2A", "#D9CCDC"], emoji: "🥻" },
      { id: "l3", title: "SoCo Saturday", vibe: "Austin easy", tags: ["casual", "color"], palette: ["#C4593A", "#F3EDE3", "#7A8B6F", "#D9B87A", "#181411"], emoji: "🌵" },
      { id: "l4", title: "Diwali Open House", vibe: "Festive, comfortable, glowing", tags: ["festival", "traditional"], palette: ["#D9B87A", "#8F3A2A", "#5C4560", "#F3EDE3", "#B8863B"], emoji: "🪔" },
      { id: "l5", title: "Monsoon Wedding Guest", vibe: "Elegant in any weather", tags: ["wedding", "guest"], palette: ["#5C4560", "#D9CCDC", "#B8863B", "#2A241F", "#EAE1D3"], emoji: "🌧️" },
    ],
    reviews: [
      { id: "r1", author: "Ananya R.", rating: 5, date: "June 2026", service: "Shaadi Season Styling", text: "Four events, four flawless looks, zero stress. She even planned outfits around the dance performances. My cousins have all taken her number." },
      { id: "r2", author: "Meera J.", rating: 5, date: "May 2026", service: "Two Worlds Wardrobe", text: "I no longer have an American closet and an Indian closet. I have MY closet. Priya understood the assignment on a level I did not expect." },
      { id: "r3", author: "Divya K.", rating: 4.8, date: "April 2026", service: "Jewel Tone Analysis", text: "First color analysis I have had that actually understood deep skin tones. The palette is stunning and completely accurate." },
    ],
    nextAvailable: "Today",
  },
  {
    id: "elena-vasquez",
    name: "Elena Vásquez",
    handle: "@elenavstyle",
    tagline: "Sustainable style with serious polish",
    city: "San Francisco",
    neighborhood: "Mission District",
    rating: 4.89,
    reviewCount: 164,
    bookings: 470,
    responseTime: "about 2 hours",
    yearsExperience: 6,
    startingPrice: 70,
    topRated: false,
    risingStar: true,
    instantBook: true,
    virtual: true,
    specialties: ["Closet Edit", "Personal Shopping", "Virtual Consult"],
    languages: ["English", "Spanish"],
    bio: "Zero waste stylist. I build stunning wardrobes from secondhand, vintage, rental and what you already own. Great style should not cost the earth, literally or figuratively.",
    approach: "The most sustainable garment is the one in your closet. We start there, then fill gaps with resale and rental before a single new item is considered.",
    brands: ["The RealReal", "Vestiaire", "ThredUp", "Nuuly", "Local vintage"],
    gradient: ["#7A8B6F", "#3E5C6B"],
    accent: "#D6DDCD",
    services: [
      { id: "s1", name: "The Zero Waste Wardrobe", category: "Closet Edit", duration: "3 hrs", price: 210, description: "Full edit with repair, tailor and restyle plans for every piece. Nothing goes to landfill, everything gets a second act.", mode: "In person" },
      { id: "s2", name: "Secondhand Safari", category: "Personal Shopping", duration: "2.5 hrs", price: 155, description: "Curated vintage and consignment circuit through the Mission. Champagne taste, thrift store receipts.", mode: "In person" },
      { id: "s3", name: "Rental Wardrobe Setup", category: "Virtual Consult", duration: "60 min", price: 70, description: "I set up and curate your rental subscriptions so you have endless novelty with zero closet guilt.", mode: "Virtual" },
    ],
    looks: [
      { id: "l1", title: "The $60 Head Turner", vibe: "All secondhand, all stunning", tags: ["thrift", "statement"], palette: ["#7A8B6F", "#C4593A", "#F3EDE3", "#181411", "#D9B87A"], emoji: "♻️" },
      { id: "l2", title: "Mended and Mightier", vibe: "Visible repair as flex", tags: ["repair", "denim"], palette: ["#3E5C6B", "#C9D8DF", "#8F3A2A", "#EAE1D3", "#2A241F"], emoji: "🪡" },
      { id: "l3", title: "Rental Rotation", vibe: "New look weekly, own nothing", tags: ["rental", "workwear"], palette: ["#5C4560", "#D6DDCD", "#B8863B", "#F3EDE3", "#181411"], emoji: "🔄" },
      { id: "l4", title: "Mission Mural Colors", vibe: "Neighborhood as palette", tags: ["color", "casual"], palette: ["#C4593A", "#D9B87A", "#3E5C6B", "#7A8B6F", "#8F3A2A"], emoji: "🎨" },
      { id: "l5", title: "The Heirloom Blazer", vibe: "1985, tailored to 2026", tags: ["vintage", "tailoring"], palette: ["#2A241F", "#D6CDBF", "#B8863B", "#EAE1D3", "#4A5843"], emoji: "🏺" },
    ],
    reviews: [
      { id: "r1", author: "Maya C.", rating: 5, date: "June 2026", service: "The Zero Waste Wardrobe", text: "She found a tailor, a cobbler and a visible mending artist for my broken favorites. My wardrobe is fully alive again and I bought nothing." },
      { id: "r2", author: "Lauren B.", rating: 4.8, date: "May 2026", service: "Secondhand Safari", text: "Came home with a full work wardrobe for $180 including a cashmere coat. I still do not understand how she does it." },
      { id: "r3", author: "Sophie T.", rating: 4.7, date: "April 2026", service: "Rental Wardrobe Setup", text: "My rental queue is now smarter than my actual shopping ever was. I get compliments weekly on clothes I return monthly." },
    ],
    nextAvailable: "Tomorrow",
  },
  {
    id: "james-okafor",
    name: "James Okafor",
    handle: "@okaforfits",
    tagline: "Big and tall styling that finally fits",
    city: "Chicago",
    neighborhood: "The Loop",
    rating: 4.95,
    reviewCount: 232,
    bookings: 720,
    responseTime: "under 1 hour",
    yearsExperience: 9,
    startingPrice: 85,
    topRated: true,
    risingStar: false,
    instantBook: true,
    virtual: true,
    specialties: ["Wardrobe Makeover", "Personal Shopping", "Event Styling"],
    languages: ["English", "Igbo"],
    bio: "Former college lineman who could never find clothes that fit, so I made it my profession. I style big and tall men who are tired of settling for whatever the back corner of the store offers.",
    approach: "Fit first, always. I keep a live database of which brands actually cut for size, the tailors who know what they are doing and the fabrics that drape instead of cling.",
    brands: ["Bonobos Extended", "DXL", "Westport Big & Tall", "State & Liberty", "Custom MTM"],
    gradient: ["#2A241F", "#3E5C6B"],
    accent: "#C9D8DF",
    services: [
      { id: "s1", name: "Finally Fits Overhaul", category: "Wardrobe Makeover", duration: "3 hrs", price: 255, description: "Complete wardrobe rebuild with my brand fit database, tailor referrals and a made to measure roadmap.", mode: "In person" },
      { id: "s2", name: "Big Man Shopping Day", category: "Personal Shopping", duration: "3 hrs", price: 200, description: "Shopping at stores I have personally vetted for extended sizing. No wasted trips, no settling.", mode: "In person" },
      { id: "s3", name: "Suit Day Done Right", category: "Event Styling", duration: "2 hrs", price: 230, description: "Wedding or big event styling with a fit guarantee. Includes tailor coordination and final fitting.", mode: "In person" },
      { id: "s4", name: "Fit Database Consult", category: "Virtual Consult", duration: "45 min", price: 85, description: "Your measurements plus my database equals a personalized list of brands and cuts that will actually fit you.", mode: "Virtual" },
    ],
    looks: [
      { id: "l1", title: "The Lineman's Suit", vibe: "Built, not squeezed", tags: ["tailoring", "big and tall"], palette: ["#2A241F", "#C9D8DF", "#B8863B", "#EAE1D3", "#181411"], emoji: "🏈" },
      { id: "l2", title: "Drape Over Cling", vibe: "Fabric that flatters", tags: ["casual", "fit"], palette: ["#3E5C6B", "#F3EDE3", "#6B6259", "#D6CDBF", "#2A241F"], emoji: "🌊" },
      { id: "l3", title: "Boardroom Presence", vibe: "Command the room", tags: ["workwear", "tailoring"], palette: ["#181411", "#B8863B", "#EAE1D3", "#3E5C6B", "#6B6259"], emoji: "🏛️" },
      { id: "l4", title: "Summer Without Suffering", vibe: "Breathable and sharp", tags: ["summer", "casual"], palette: ["#F3EDE3", "#C9D8DF", "#7A8B6F", "#D9B87A", "#2A241F"], emoji: "☀️" },
      { id: "l5", title: "Game Day Host", vibe: "Casual authority", tags: ["weekend", "casual"], palette: ["#8F3A2A", "#EAE1D3", "#2A241F", "#C4593A", "#D6CDBF"], emoji: "🍖" },
    ],
    reviews: [
      { id: "r1", author: "Big Mike D.", rating: 5, date: "June 2026", service: "Finally Fits Overhaul", text: "6 foot 6, 320 pounds, and for the first time in my adult life my clothes fit ME instead of the other way around. James is doing sacred work." },
      { id: "r2", author: "Carl W.", rating: 5, date: "May 2026", service: "Suit Day Done Right", text: "Stood next to my groomsmen looking like the best dressed man in the building, because I was. The fit guarantee is real." },
      { id: "r3", author: "Andre P.", rating: 4.8, date: "April 2026", service: "Fit Database Consult", text: "That database is worth ten times the price. Ordered from three brands he listed, kept everything. That has literally never happened." },
    ],
    nextAvailable: "Today",
  },
];

export function getStylist(id: string): Stylist | undefined {
  return STYLISTS.find((s) => s.id === id);
}

export function formatMoney(n: number): string {
  return `$${n.toLocaleString("en-US", { maximumFractionDigits: 2 })}`;
}
